version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
      JWT_SECRET: $JWT_SECRET

    depends_on:
      - "db"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - "5432"
    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin-data:

networks:
  default:
    name: app


